blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'


urlpatterns = [

    # Post
    path('', post_list, name='post_all'),
    path('<slug:main_category_slug>/<slug:category_slug>/', post_list, name='post_in_category'),  
    path('post/<int:post_id>/', post_detail, name='post_detail'),
    path('post/<slug:category_slug>/create/', post_create, name='post_create'),
    path('post/<int:post_id>/update/', post_update, name='post_update'),
    path('post/<int:post_id>/delete/', post_delete, name='post_delete'), # delete 기능은 jQuery를 쓸 예정.
    
    # Comment
    path('post/<int:post_id>/comment/create', comment_create, name='comment_create'),
    path('post/comment/<int:comment_id>/update', comment_update, name='comment_update'),
    path('post/comment/<int:comment_id>/delete', comment_delete, name='comment_delete'),

    # recommend
    path('post/<int:post_id>/recommend', post_recommend, name='post_recommend'),
    path('post/comment/<int:comment_id>/recommend', comment_recommend, name='comment_recommend'),
 
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.

class MainCategory(models.Model):
    name = models.CharField(max_length=100, db_index=True, unique=True)
    slug = models.SlugField(max_length=1100, db_index=True, unique=True)    

    class Meta:
        ordering = ['name']
        verbose_name = 'main category'
        verbose_name_plural = 'main categories'
    
    def __str__(self):
        return self.name    


class Category(models.Model):

    main_category = models.ForeignKey(MainCategory, on_delete=models.SET_NULL, null= True)
    name = models.CharField(max_length=100, db_index= True, unique= True)
    description = models.TextField()
    slug = models.SlugField(max_length=100, db_index= True, unique= True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('blog:post_in_category', args=[self.main_category.slug, self.slug])
    

class Post(models.Model):
    
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null= True)    
    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    display = models.BooleanField('Display', default=True)
    recommend = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True, null= True) # 추천 기능

    def __str__(self):
        return self.title

    def get_absoulute_url(self):
        return reverse('blog:post_detail', args=[self.id])


class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comment_authors')
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(blank=True, null= True)
    recommend = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True, null= True, related_name='commend_recommends') # 추천 기능

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content']
        labels = {
            
            'title' : '제목',
            'content' : '내용'
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content' : '내용'}

blog/views.py
from datetime import time
from django.shortcuts import render,get_object_or_404,redirect,resolve_url
from .models import *
from .forms import *
from django.utils import timezone
from django.core.paginator import Paginator # Paginator 호출
from django.contrib.auth.decorators import login_required # login 데코레이터
from django.contrib import messages
from django.db.models import Q, Count, F
# Create your views here.

def post_list(request, main_category_slug=None, category_slug = None):
    # Category filtering
    current_category = None  
    categories = Category.objects.all()
    posts = Post.objects.filter(display=True)

    if main_category_slug and category_slug:
        main_category = get_object_or_404(MainCategory, slug = main_category_slug)
        current_category = get_object_or_404(Category, main_category = main_category, slug = category_slug)
        posts = posts.filter(category = current_category)
    

    # 페이징/ 검색/ 정렬 파라미터
    page = request.GET.get('page', '1') 
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    # Search
    if kw:
        posts = posts.filter(
            Q(title__icontains=kw)|
            Q(content__icontains=kw)|
            Q(comment__content__icontains=kw)        
        )

    # Sorting
    if so == 'recommend':
        posts = posts.annotate(num_recommend = Count('recommend')).order_by('-num_recommend', '-created_date')    
    elif so == 'popular':
        posts = posts.annotate(num_comment = Count('comments')).order_by('-num_comment', '-created_date')
    else:   # 'recent'
        posts = posts.order_by('-created_date')    
    
    
    # Paginator    
    paginator = Paginator(posts, '9')
    page_obj = paginator.get_page(page)
    

    context = {'categories':categories, 'current_category':current_category, 'posts':page_obj, 'page':page, 'kw':kw, 'so':so}

    return render(request, 'blog/post_list.html', context=context)

def post_detail(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    context = {'post':post}
    
    return render(request, 'blog/post_detail.html', context=context)


def post_create(request, category_slug = None):
    current_category = None
    if category_slug:
        current_category = get_object_or_404(Category, slug = category_slug)
    
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data            
            post = Post(title = cd['title'], content = cd['content'], category = current_category)
            post.save()
            return redirect('blog:post_detail', post.id)
    else:
        form = PostForm()
    context = {'form':form}
    
    return render(request, 'blog/post_form.html', context)

def post_update(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.updated_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', id=post.id)
    
    else:
        form = PostForm(instance=post)

    context = {'form':form}
    
    return render(request, 'blog/post_form.html', context)


def post_delete(request, post_id):
        
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('blog:post_all')


#---------------------- Comment ------------------------#

@login_required
def comment_create(request, post_id):

    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('blog:post_detail', post.id), comment.id))   
    else:
        form = CommentForm()
    context = {'post':post,'form':form}
    return render(request, 'blog/post_detail.html', context)


@login_required
def comment_update(request, comment_id):

    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.updated_date = timezone.now()
            comment.save()
            return  redirect('{}#comment_{}'.format(resolve_url('blog:post_detail', comment.post.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form':form}
    return render(request, 'blog/comment_form.html', context)


@login_required
def comment_delete(request, comment_id):
    
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return  redirect('blog:post_detail', post_id=comment.post.id)

#---------------------- Recommend ------------------------#

@login_required
def post_recommend(request, post_id):

    post = get_object_or_404(Post, id=post_id)
    user = request.user
    
    if user.is_superuser:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        post.recommend.add(request.user)
    return redirect('blog:post_detail', post.id)

@login_required
def comment_recommend(request, comment_id):
    
    comment = get_object_or_404(Comment, id=comment_id)

    if request.user == comment.author:
        messages.error(request, '본인이 작성한 댓글은 추천할 수 없습니다.')
    else:
        comment.recommend.add(request.user)
    return redirect('{}#comment_{}'.format(resolve_url('blog:post_detail', comment.post.id), comment.id))

 

templates/blog/comment_form.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <div class="container my-3">            
        <form method="POST" class="post-form my-3">
            {% csrf_token %}           
            <div class="form-group">
                <label for="content">Add comment:</label>
                <textarea class="form-control"name="content" id="content" 
                        rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
</div>

{% endblock %}  

templates/blog/post_detail.html
{% extends "base.html" %}
{% block content %}


<div class="jumbotron"> 
     <!-- 사용자오류 표시 -->
     {% if messages %}
     <div class="alert alert-danger my-3" role="alert">
     {% for message in messages %}
         <strong>{{ message.tags }}</strong>
         <ul><li>{{ message.message }}</li></ul>
     {% endfor %}
     </div>
     {% endif %}

    <div class="container my-3">
        <div class="badge badge-light p-2 text-left">                        
            <div>{{ post.category }}</div>
        </div>
        <h2 class="border-bottom py-2">{{ post.title }}</h2>   
        <div class="row my-3">
            <div class="col-1"> <!-- Recommend start -->
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{post.recommend.count}}</div>
                <a href="{% url 'blog:post_recommend' post.id  %}" 
                   class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
                   <!-- Recommend end -->
            </div>
            <div class="col-11">   
                <div class="card">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line;">{{ post.content|safe|linebreaksbr }}</div>
                        <div class="d-flex justify-content-end">
                            <div class="badge badge-light p-2 text-left">                        
                                <div>{{ post.created_date }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
        </div>                
    </div>

    {% if user.is_superuser %}
    <div class="my-3">
        <a href="{% url 'blog:post_update' post.id  %}"
            class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="#" class="delete btn btn-sm btn-outline-secondary"
            data-uri="{% url 'blog:post_delete' post.id  %}">삭제</a>
    </div>
    {% endif %}
    
    
        <!-- Comment start -->
        {% if post.comments.count > 0 %}
        <h5 class="border-bottom my-3 py-2">{{post.comments.count}}개의 답변이 있습니다.</h5>
        <div class="mt-3">
        {% for comment in post.comments.all %}  <!-- 등록한 댓글을 출력 -->
            <a name="comment_{{ comment.id }}"></a><!-- 앵커 태그 -->
            <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                <span style="white-space: pre-line;">{{ comment.content }}</span>
                <span>
                    - {{ comment.author.username }}, {{ comment.created_date }}
                    {% if comment.updated_date %}
                    (updated:{{ comment.updated_date }})
                    {% endif %}
                </span>
                <p class="card-text"><span class="badge badge-secondary">추천: {{comment.recommend.count}}</span></p>
                
                {% if user.is_authenticated %}                
                <a href="{% url 'blog:comment_recommend' comment.id  %}" class="small">추천</a>,
                    {% if request.user == comment.author %}
                    <a href="{% url 'blog:comment_update' comment.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete" 
                    data-uri="{% url 'blog:comment_delete' comment.id %}">삭제</a>
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}
        </div>
        {% endif %}

        <div class="container my-3">            
            <form method="POST" class="post-form my-3" action="{% url 'blog:comment_create' post.id %}">
                {% csrf_token %}           
                <div class="form-group">
                    <label for="content">Add comment:</label>
                    {% if not user.is_authenticated %}
                    <textarea class="form-control"name="content" id="content" 
                            rows="3" disabled>{{ form.content.value|default:'댓글 작성을 위해 로그인 해주세요.' }}</textarea>
                    {% else %}        
                    <textarea class="form-control"name="content" id="content" 
                            rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
                    {% endif %}        
                </div>
                <button type="submit" class="btn btn-primary" {% if not user.is_authenticated %}disabled{% endif %}>저장하기</button>
            </form>
        </div>
        
        <!-- Comment end -->

</div>

{% endblock %}  

{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("Are you sure to delete this?")) {
                location.href = $(this).data('uri');
            }
    
        });
       
    });
    </script>
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">New post</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        
        <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">Content:</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">
        <div class="col-2">
            <div class="list-group">
                <a href="/" class='list-group-item {% if not current_category %}active{% endif %}'>All</a>
                {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}" 
                    class='list-group-item {% if current_category.slug == category.slug %}active{% endif %}'>{{ category.name }}</a>
                {% endfor %}    
            </div>
        </div>
        

        <div class="col">
            
            <div class="alert alert-info" role='alert'>
                {% if current_category %}{{current_category.name}}{% else %}All Articles{% endif %}
            </div>
            {% if current_category %}
            <a href="{% url 'blog:post_create' current_category.slug %}" class="btn btn-primary">New Post</a>
            {% endif %}
            
            <!-- 정렬 select 옵션 -->
            <div class="row justify-content-between my-3">  
                <div class="col-2">
                    <select class="form-control so">
                        <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                        <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                        <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>                        
                    </select>
                </div>
            <!-- end 정렬 select 옵션  -->
            
            <!-- 검색 창 -->
                <div class="col-4 input-group">
                    <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                    </div>
                </div>
            </div>
            <!-- end 검색 창  -->
            

            <div class="row">
            {% if posts %}
                {% for post in posts %}
                <div class="col-4">
                    <div class="card">                        
                        <div class="card-body">
                            <p class="card-text"><span class="badge badge-secondary">{{post.category.name}}</span></p>
                            <h5 class="card-title">{{post.title}}</h5>
                            {% if post.comments.count > 0 %}
                            <span class="text-danger small ml-2">{{ post.comments.count }}</span>
                            {% endif %}                            
                                <p class="card-text"><span class="badge badge-secondary">{{post.created_date}}</span></p>
                        <a href="{% url 'blog:post_detail' post.id %}" class='btn btn-primary'>View Detail</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}         
            
        </div>
            
    </div>
    <div class="container">
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" page-date="{{ posts.previous_page_number }}" href="#">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in posts.paginator.page_range %}
            {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
                {% if page_number == posts.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" date-page="{{ page_number }}" href="#">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" date-page="{{ page_number }}" href="#">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ posts.next_page_number }}" href="#">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </div>

    <!-- 검색/정렬/페이징 form -->
    <form id="searchForm" method="get">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="so" name="so" value="{{ so }}">
    </form>
    <!-- end 검색/정렬/페이징 form -->
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}