blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'


urlpatterns = [

    # Post
    path('', post_list, name='post_all'),
    path('<slug:main_category_slug>/<slug:category_slug>/', post_list, name='post_in_category'),  
    path('post/<int:post_id>/', post_detail, name='post_detail'),
    path('post/<slug:category_slug>/create/', post_create, name='post_create'),
    path('post/<int:post_id>/update/', post_update, name='post_update'),
    path('post/<int:post_id>/delete/', post_delete, name='post_delete'), # delete 기능은 jQuery를 쓸 예정.
    
    # Comment
    path('post/<int:post_id>/comment/create', comment_create, name='comment_create'),
    path('post/comment/<int:comment_id>/update', comment_update, name='comment_update'),
    path('post/comment/<int:comment_id>/delete', comment_delete, name='comment_delete'),

    # recommend
    path('post/<int:post_id>/recommend', post_recommend, name='post_recommend'),
    path('post/comment/<int:comment_id>/recommend', comment_recommend, name='comment_recommend'),
 
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <title> My Dev Blog </title>

    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,200;0,300;1,200&family=Fira+Sans&family=Roboto&display=swap" rel="stylesheet">
   
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
   
</head>
<body>
  {% include "navbar.html" %}

  {% block content %}

  {% endblock %}  

    


  <!-- J query script-->
  <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
  {% block script %}
  {% endblock %}

</body>
</html>

templates/navbar.html
<div class="container varelafont">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark varelafont">
      <a class="navbar-brand" href='{% url "blog:post_all" %}'>Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href='{% url "blog:post_all" %}'>Post<span class="sr-only">(current)</span></a>
            </li>                         
          </ul>
      </div>
      
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link " aria-current="page" href="{% url 'account_logout' %}">{{user.username}} (LOGOUT)</a>
            {% else %}
            <a class="nav-link " aria-current="page" href="{% url 'account_login' %}">LOGIN</a>
            <a class="nav-link " aria-current="page" href="{% url 'account_signup' %}">SIGNUP</a>            
            {% endif %}
          </li>     
      </div>
        
   
    </nav>   